Задание 1

Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [1]:
import pandas as pd

In [42]:
ratings = pd.read_csv('ratings.csv')
# ratings.head()
movies = pd.read_csv('movies.csv')
# movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [69]:
# ratings.info()
ratings_movies = ratings.merge(movies, on = 'movieId', how='left')
# ratings_movies.head()

rating5_movies = ratings_movies[ratings_movies['rating']==5]
# rating5_movies.head()

rating5_movies['title'].value_counts().head(1)

Shawshank Redemption, The (1994)    153
Name: title, dtype: int64

Задание 2

По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [11]:
data = pd.read_csv('power.csv')

In [39]:
# data.head()

data_filtered = data[data['country'].isin(['Lithuania','Estonia','Latvia']) & data['category'].isin([4,12,21]) & (data['year']<2010) & (data['year']>2005) & data['quantity']>0]

data_filtered.quantity.sum()

164486.0

Задание 3

Выберите страницу любого сайта с табличными данными. Импортируйте таблицы в pandas dataframe.
Примеры страниц (необязательно брать именно эти):
https://fortrader.org/quotes
https://www.finanz.ru/valyuty/v-realnom-vremeni

In [57]:
page_url = 'https://www.finanz.ru/valyuty/v-realnom-vremeni'

In [59]:
df = pd.read_html(page_url, attrs = {'class': 'header_user_pricebox'}, encoding='utf-8')

In [61]:
df[0]

,0,1,2,3,4,5,6,7,8,9,10,11
0,ММВБ,2 758,"1,8%",Nasdaq,9 325,"0,4%",Биткойн,8 926,"0,3%",USD/RUB,715020,"-0,1%"
1,РТС,1 213,"2,1%",S&P500,2 955,"0,2%",Нефть,360,"1,1%",EUR/RUB,780920,"0,2%"
2,Dow,24 465,"0,0%",FTSE100,5 993,"-0,4%",Золото,1 734,"0,3%",EUR/USD,10919,"0,2%"

In [68]:
pd.read_html('https://www.finanz.ru/valyuty/v-realnom-vremeni', encoding='utf-8')[1]

,Unnamed: 0,Рубль,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
0,NaN,GBP/RUB,874497,-,872295,"0,25 %",02202,19:05:00
1,NaN,EUR/RUB,777980,-,779215,"-0,16 %",-01235,19:04:00
2,NaN,USD/RUB,708735,-,715665,"-0,97 %",-06930,19:04:00
3,NaN,JPY/RUB,06584,-,06644,"-0,90 %",-00060,19:05:00
4,NaN,CNY/RUB,99342,-,100275,"-0,93 %",-00933,19:04:00
5,NaN,CHF/RUB,733070,-,736332,"-0,44 %",-03262,19:04:00
6,NaN,Евро,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
7,NaN,EUR/USD,10969,-,10895,"0,68 %",00075,19:04:00
8,NaN,EUR/GBP,08891,-,08936,"-0,50 %",-00045,19:04:00
9,NaN,EUR/JPY,1180920,-,1173300,"0,65 %",07620,19:04:00
10,NaN,EUR/CHF,10608,-,10586,"0,21 %",00022,19:04:00
11,NaN,Доллар США,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
12,NaN,USD/EUR,09115,-,09180,"-0,70 %",-00064,19:04:00
13,NaN,USD/GBP,08105,-,08204,"-1,21 %",-00099,19:04:00
14,NaN,USD/JPY,1076500,-,1077150,"-0,06 %",-00650,19:04:00
15,NaN,USD/CHF,09671,-,09716,"-0,46 %",-00045,19:04:00
16,NaN,Японская иена,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
17,NaN,JPY/EUR (100:1),08500,-,08500,"-0,64 %",-00001,19:05:00
18,NaN,JPY/GBP,00075,-,00076,"-1,15 %",-00001,19:05:00
19,NaN,JPY/USD,00093,-,00093,"0,06 %",00000,19:05:00
20,NaN,JPY/CHF (100:1),09000,-,09000,"-0,42 %",00000,19:04:00
21,NaN,Фунт стерлингов,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
22,NaN,GBP/USD,12339,-,12191,"1,21 %",00148,19:04:00
23,NaN,GBP/JPY,1328223,-,1312926,"1,17 %",15297,19:05:00
24,NaN,GBP/EUR,11247,-,11188,"0,53 %",00059,19:04:00
25,NaN,GBP/CHF,11932,-,11843,"0,75 %",00089,19:04:00
26,NaN,Швейцарский франк,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
27,NaN,GBP/CHF,11932,-,11843,"0,75 %",00089,19:04:00
28,NaN,EUR/CHF,10608,-,10586,"0,21 %",00022,19:04:00
29,NaN,JPY/CHF (100:1),09000,-,09000,"-0,42 %",00000,19:04:00
30,NaN,USD/CHF,09671,-,09716,"-0,46 %",-00045,19:04:00
31,NaN,Украинская гривна,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
32,NaN,EUR/UAH,295469,-,291737,"1,28 %",03732,19:04:00
33,NaN,USD/UAH,269355,-,267808,"0,58 %",01547,19:03:00
34,NaN,CHF/UAH,278519,-,275552,"1,08 %",02967,19:04:00
35,NaN,GBP/UAH,332330,-,326431,"1,81 %",05899,19:04:00